# Generated by Django 4.2 on 2023-06-13 04:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerceapp", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="customer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_review",
                to="ecommerceapp.customer",
            ),
            preserve_default=False,
        ),
    ]
