# Generated by Django 4.2 on 2023-06-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_review_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
